-- Type: account_type

-- Safely drop the tables and types, handling dependencies
DROP TABLE IF EXISTS public.inventory CASCADE;
DROP TABLE IF EXISTS public.classification CASCADE;
DROP TABLE IF EXISTS public.account CASCADE;
DROP TYPE IF EXISTS public.account_type;

-- Create account_type enum type
CREATE TYPE public.account_type AS ENUM
    ('Client', 'Employee', 'Admin');

-- Table structure for table `classification`
CREATE TABLE public.classification (
	classification_id INT GENERATED BY DEFAULT AS IDENTITY,
	classification_name CHARACTER VARYING NOT NULL,
	CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- Table structure for table `inventory`
CREATE TABLE public.inventory
(
	inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	inv_make character varying NOT NULL,
	inv_model character varying NOT NULL,
	inv_year character(4) NOT NULL,
	inv_description text NOT NULL,
	inv_image character varying NOT NULL,
	inv_thumbnail character varying NOT NULL,
	inv_price numeric(9, 0) NOT NULL,
	inv_miles integer NOT NULL,
	inv_color character varying NOT NULL,
	classification_id integer NOT NULL,
	CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

-- Create relationship between `classification` and `inventory` tables
ALTER TABLE public.inventory
	ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id)
	REFERENCES public.classification (classification_id) MATCH SIMPLE
	ON UPDATE CASCADE
	ON DELETE NO ACTION;

-- Table structure for table `account`
CREATE TABLE public.account
(
	account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	account_firstname character varying NOT NULL,
	account_lastname character varying NOT NULL,
	account_email character varying NOT NULL,
	account_password character varying NOT NULL,
	account_type account_type NOT NULL DEFAULT 'Client'::account_type,
	CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- Data for table `classification`
INSERT INTO public.classification (classification_name)
VALUES
('Custom'),
('Sport'),
('SUV'),
('Truck'),
('Sedan');

-- Data for table `inventory`
INSERT INTO public.inventory (
    inv_make,
    inv_model,
    inv_year,
    inv_description,
    inv_image,
    inv_thumbnail,
    inv_price,
    inv_miles,
    inv_color,
    classification_id
  )
VALUES   
  ('Chevy', 'Camaro', '2018', 'If you want to look cool, this is the car for you! This car has great performance at an affordable price. Own it today!', '/images/camaro.jpg', '/images/camaro-tn.jpg', 25000, 101222, 'Silver', 2),
  ('Batmobile', 'Custom', '2007', 'Ever want to be a superhero? Now you can with the Batmobile. This car allows you to switch to bike mode for maneuvering through traffic.', '/images/batmobile.jpg', '/images/batmobile-tn.jpg', 65000, 29887, 'Black', 1),
  ('FBI', 'Surveillance Van', '2016', 'Do you like police shows? You will feel right at home driving this van. Comes complete with surveillance equipment for an extra fee.', '/images/survan.jpg', '/images/survan-tn.jpg', 20000, 19851, 'Brown', 1),
  ('Dog', 'Car', '1997', 'Do you like dogs? This car from Aspen, Colorado is the original Dog Car with fluffy ears.', '/images/dog-car.jpg', '/images/dog-car-tn.jpg', 35000, 71632, 'White', 1),
  ('Jeep', 'Wrangler', '2019', 'The Jeep Wrangler is small and compact with enough power for everyday driving and offroading!', '/images/wrangler.jpg', '/images/wrangler-tn.jpg', 28045, 41205, 'Yellow', 3),
  ('Lamborghini', 'Adventador', '2016', 'This V-12 engine packs a punch. Make sure you wear your seatbelt and obey all traffic laws.', '/images/adventador.jpg', '/images/adventador-tn.jpg', 417650, 71003, 'Blue', 2),
  ('Aerocar International', 'Aerocar', '1963', 'Sick of rush-hour traffic? This car converts into an airplane! Only 6 were made. Get them while they last!', '/images/aerocar.jpg', '/images/aerocar-tn.jpg', 700000, 18956, 'Red', 1),
  ('Monster', 'Truck', '1995', 'This beast comes with 60-inch tires for jumping and rolling in the mud.', '/images/monster-truck.jpg', '/images/monster-truck-tn.jpg', 150000, 3998, 'Purple', 1),
  ('Cadillac', 'Escalade', '2019', 'The luxurious Cadillac Escalade is great for any occasion, from the beach to meeting the president.', '/images/escalade.jpg', '/images/escalade-tn.jpg', 75195, 41958, 'Black', 4),
  ('GM', 'Hummer', '2016', 'The Hummer is perfect for large families who love offroading.', '/images/hummer.jpg', '/images/hummer-tn.jpg', 58800, 56564, 'Yellow', 4),
  ('Mechanic', 'Special', '1964', 'With some TLC, this car will run like new.', '/images/mechanic.jpg', '/images/mechanic-tn.jpg', 100, 200125, 'Rust', 5),
  ('Ford', 'Model T', '1921', 'The Ford Model T was the first car put into production. You can get it in any color as long as it is black.', '/images/model-t.jpg', '/images/model-t-tn.jpg', 30000, 26357, 'Black', 5),
  ('Mystery', 'Machine', '1999', 'The Mystery Machine will help you solve any mystery, just like Scooby and the gang.', '/images/mystery-van.jpg', '/images/mystery-van-tn.jpg', 10000, 128564, 'Green', 1),
  ('Spartan', 'Fire Truck', '2012', 'Be prepared for emergencies with this Spartan fire truck. Comes with a 1000 ft. hose and a 1000-gallon tank.', '/images/fire-truck.jpg', '/images/fire-truck-tn.jpg', 50000, 38522, 'Red', 4),
  ('Ford', 'Crown Victoria', '2013', 'After the police upgraded their fleet, these Crown Victorias are available to the public. Great for college students.', '/images/crwn-vic.jpg', '/images/crwn-vic-tn.jpg', 10000, 108247, 'White', 5);

-- Insert sample account data
INSERT INTO public.account (account_firstname, account_lastname, account_email, account_password)
VALUES ('Tony', 'Stark', 'tony@starkent.com', 'Iam1ronM@n');

-- Update account to Admin
UPDATE public.account
SET account_type = 'Admin'
WHERE account_id = 1;

-- Delete account
DELETE FROM public.account WHERE account_id = 1;

-- Update inventory description
UPDATE public.inventory
SET inv_description = REPLACE(inv_description, 'the small interiors', 'a huge interior')
WHERE inv_id = 10;

-- Select inventory with classification 'Sport'
SELECT inv_make, inv_model FROM public.inventory
INNER JOIN public.classification
ON public.inventory.classification_id = public.classification.classification_id
WHERE public.classification.classification_id = 2;

-- Update image paths
UPDATE public.inventory 
SET 
    inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'), 
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/')
WHERE 
    inv_image LIKE '/images/%' 
    AND inv_image NOT LIKE '/images/vehicles/%';